# Generated by Django 3.2 on 2021-04-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя пользователя')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='Email')),
                ('dateOfBirth', models.DateField(blank=True, verbose_name='Дата рождения')),
            ],
        ),
    ]
