# Generated by Django 3.2 on 2021-04-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
    ]
