# Generated by Django 3.2 on 2021-04-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210407_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='ip',
            field=models.CharField(default='', max_length=30, verbose_name='Ip'),
            preserve_default=False,
        ),
    ]
