# Generated by Django 3.2 on 2021-04-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='members',
            field=models.TextField(default='', verbose_name='Участники чата через пробел'),
            preserve_default=False,
        ),
    ]
