# Generated by Django 3.2 on 2021-04-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chat_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='members',
            field=models.TextField(null=True, verbose_name='Участники чата через пробел'),
        ),
    ]
