# Generated by Django 3.2 on 2021-04-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chat_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='members',
            field=models.TextField(blank=True, null=True, verbose_name='Участники чата через пробел'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='ip',
            field=models.TextField(blank=True, verbose_name='Ip, если несколько, через пробел:'),
        ),
    ]
