# Generated by Django 3.2 on 2021-04-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20210408_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='lastPC',
            field=models.CharField(default='WIN-DFD3304QAUS', max_length=50, verbose_name='Последнее устройство'),
        ),
    ]
