# Generated by Django 3.2 on 2021-04-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_chatuser_lastpc'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='lastMassageTime',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего сообщения'),
        ),
    ]
