# Generated by Django 3.2 on 2021-04-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_chatuser_lastmassagetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatuser',
            name='lastMassageTime',
        ),
        migrations.AddField(
            model_name='chat',
            name='lastMassageTime',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего сообщения'),
        ),
    ]
