# Generated by Django 3.2 on 2021-04-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20210418_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='lastMassageTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего сообщения'),
        ),
    ]
