# Generated by Django 3.2 on 2021-04-18 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_chat_lastmassagetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'get_latest_by': '-lastMessageTime'},
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='lastMassageTime',
            new_name='lastMessageTime',
        ),
    ]
