# Generated by Django 3.2 on 2021-04-18 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_auto_20210418_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'get_latest_by': 'lastMessageTime'},
        ),
    ]
