# Generated by Django 3.2 on 2021-04-18 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_alter_chat_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={},
        ),
    ]
