# Generated by Django 3.2 on 2021-04-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_alter_chat_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='имя пользователя'),
        ),
    ]
