# Generated by Django 3.2 on 2021-05-09 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_alter_message_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='viewed',
        ),
    ]
